import type { Metadata } from "next";
import { Jersey_15 } from "next/font/google";
import "./globals.css";
import { BackgroundBeams } from "@/components/ui/background-beams";



const jersey = Jersey_15({

  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${jersey.className} antialiased bg-zinc-900`}
      >
        <BackgroundBeams />
        {children}
      </body>
    </html>
  );
}
