import type { Metadata } from "next";
import { Jersey_15 } from "next/font/google";
import "./globals.css";
import { BackgroundBeams } from "@/components/ui/background-beams";
import NavBar from "@/components/NavBar";

import { auth } from "./auth";
import SessionProviderComponent from "@/components/SessionProviderComponent";



const jersey = Jersey_15({

  subsets: ["latin"],
  weight: "400"
})

const session = await auth();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${jersey.className} antialiased bg-zinc-900 scroll-m-0 flex flex-col justify-center items-center`}
      >
        <SessionProviderComponent session={session}>
        <BackgroundBeams className="z-[-10]"/>
        <NavBar />
        {children}
        </SessionProviderComponent>
      </body>
    </html>
  );
}
